"""phase3_auditability

Revision ID: 010ecf8ca591
Revises: 2046d4ea5dd6
Create Date: 2026-07-24 08:50:03.532411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '010ecf8ca591'
down_revision: Union[str, Sequence[str], None] = '2046d4ea5dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_vouchers', sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', 'VOID', name='voucherstatus'), nullable=True))
    op.add_column('bank_vouchers', sa.Column('finalized_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'bank_vouchers', ['check_number'])
    op.add_column('caisse_vouchers', sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', 'VOID', name='voucherstatus'), nullable=True))
    op.add_column('caisse_vouchers', sa.Column('finalized_at', sa.DateTime(), nullable=True))
    op.drop_column('caisse_vouchers', 'recettes')
    op.drop_column('caisse_vouchers', 'depenses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caisse_vouchers', sa.Column('depenses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('caisse_vouchers', sa.Column('recettes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('caisse_vouchers', 'finalized_at')
    op.drop_column('caisse_vouchers', 'status')
    op.drop_constraint(None, 'bank_vouchers', type_='unique')
    op.drop_column('bank_vouchers', 'finalized_at')
    op.drop_column('bank_vouchers', 'status')
    # ### end Alembic commands ###
