"""add_voucher_fks

Revision ID: 2046d4ea5dd6
Revises: 4aaf96f057d9
Create Date: 2026-07-24 08:47:04.851679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2046d4ea5dd6'
down_revision: Union[str, Sequence[str], None] = '4aaf96f057d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_vouchers', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('bank_vouchers', sa.Column('expense_id', sa.Integer(), nullable=True))
    op.add_column('bank_vouchers', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bank_vouchers', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bank_vouchers', 'project_expenses', ['expense_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bank_vouchers', 'project_stock_reservations', ['reservation_id'], ['id'], ondelete='SET NULL')
    op.add_column('caisse_vouchers', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('caisse_vouchers', sa.Column('expense_id', sa.Integer(), nullable=True))
    op.add_column('caisse_vouchers', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'caisse_vouchers', 'project_expenses', ['expense_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'caisse_vouchers', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'caisse_vouchers', 'project_stock_reservations', ['reservation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'caisse_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'caisse_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'caisse_vouchers', type_='foreignkey')
    op.drop_column('caisse_vouchers', 'reservation_id')
    op.drop_column('caisse_vouchers', 'expense_id')
    op.drop_column('caisse_vouchers', 'project_id')
    op.drop_constraint(None, 'bank_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'bank_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'bank_vouchers', type_='foreignkey')
    op.drop_column('bank_vouchers', 'reservation_id')
    op.drop_column('bank_vouchers', 'expense_id')
    op.drop_column('bank_vouchers', 'project_id')
    # ### end Alembic commands ###
