"""migrate_float_to_numeric

Revision ID: 4aaf96f057d9
Revises: f0e5849fed4f
Create Date: 2026-07-24 08:37:15.734105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aaf96f057d9'
down_revision: Union[str, Sequence[str], None] = 'f0e5849fed4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analytical_allocations', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('bank_vouchers', 'amount_in_numbers',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('project_budgets', 'allocated_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('project_expenses', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'budget_estime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('projects', 'budget_engage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('purchase_order_lines', 'unit_price',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('purchase_order_lines', 'unit_price',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('projects', 'budget_engage',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('projects', 'budget_estime',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('project_expenses', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('project_budgets', 'allocated_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('bank_vouchers', 'amount_in_numbers',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('analytical_allocations', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
