"""Initial migration

Revision ID: 4ca9f05c0207
Revises: 
Create Date: 2026-07-20 08:53:05.612250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca9f05c0207'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('employee_documents', 'category',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('IDENTITY', 'SOCIAL', 'CONTRACT', name='documentcategory'),
               existing_nullable=False,
               postgresql_using="category::text::documentcategory")
    op.alter_column('facility_requests', 'request_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('MAINTENANCE', 'PURCHASE', 'OTHER', name='facilityrequesttype'),
               existing_nullable=False,
               postgresql_using="request_type::text::facilityrequesttype")
    op.alter_column('facility_requests', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'APPROVED', 'REJECTED', name='facilityrequeststatus'),
               nullable=True,
               postgresql_using="status::text::facilityrequeststatus")
    op.alter_column('facility_requests', 'rejection_comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('fuel_requests', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('fuel_requests', 'status',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('PENDING_LOGISTICS', 'PENDING_FINANCE', 'APPROVED', 'REJECTED', name='fuelrequeststatus'),
               existing_nullable=True,
               postgresql_using="status::text::fuelrequeststatus")
    op.create_foreign_key(None, 'fuel_requests', 'projects', ['project_id'], ['id'])
    op.alter_column('hr_requests', 'request_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('LEAVE', 'DOCUMENT', 'OTHER', name='hrrequesttype'),
               existing_nullable=False,
               postgresql_using="request_type::text::hrrequesttype")
    op.alter_column('hr_requests', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'RESOLVED', 'CLOSED', name='hrrequeststatus'),
               existing_nullable=True,
               postgresql_using="status::text::hrrequeststatus")
    op.alter_column('hr_requests', 'rejection_comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('it_requests', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'APPROVED', 'REJECTED', name='itrequeststatus'),
               nullable=True,
               postgresql_using="status::text::itrequeststatus")
    op.alter_column('it_requests', 'rejection_comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.execute("ALTER TABLE leave_requests ALTER COLUMN status DROP DEFAULT")
    op.alter_column('leave_requests', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'),
               existing_nullable=True,
               postgresql_using="status::text::leavestatus")
    op.execute("ALTER TABLE leave_requests ALTER COLUMN status SET DEFAULT 'PENDING'::leavestatus")
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.alter_column('stock_movements', 'type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('ENTRY', 'EXIT', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', name='movementtype'),
               existing_nullable=False,
               postgresql_using="type::text::movementtype")
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'ARCHIVED', name='taskstatus'),
               existing_nullable=False,
               postgresql_using="status::text::taskstatus")
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', name='taskpriority'),
               existing_nullable=False,
               postgresql_using="priority::text::taskpriority")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', name='taskpriority'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'ARCHIVED', name='taskstatus'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('stock_movements', 'type',
               existing_type=sa.Enum('ENTRY', 'EXIT', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', name='movementtype'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.alter_column('leave_requests', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.alter_column('it_requests', 'rejection_comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('it_requests', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'APPROVED', 'REJECTED', name='itrequeststatus'),
               type_=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('hr_requests', 'rejection_comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('hr_requests', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'RESOLVED', 'CLOSED', name='hrrequeststatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('hr_requests', 'request_type',
               existing_type=sa.Enum('LEAVE', 'DOCUMENT', 'OTHER', name='hrrequesttype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_constraint(None, 'fuel_requests', type_='foreignkey')
    op.alter_column('fuel_requests', 'status',
               existing_type=sa.Enum('PENDING_LOGISTICS', 'PENDING_FINANCE', 'APPROVED', 'REJECTED', name='fuelrequeststatus'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.drop_column('fuel_requests', 'project_id')
    op.alter_column('facility_requests', 'rejection_comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('facility_requests', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'APPROVED', 'REJECTED', name='facilityrequeststatus'),
               type_=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('facility_requests', 'request_type',
               existing_type=sa.Enum('MAINTENANCE', 'PURCHASE', 'OTHER', name='facilityrequesttype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('employee_documents', 'category',
               existing_type=sa.Enum('IDENTITY', 'SOCIAL', 'CONTRACT', name='documentcategory'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    # ### end Alembic commands ###
