"""Add linked_caisse_voucher_ids to BankVoucher

Revision ID: ca916c10e41b
Revises: 010ecf8ca591
Create Date: 2026-07-24 11:25:30.014261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca916c10e41b'
down_revision: Union[str, Sequence[str], None] = '010ecf8ca591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_vouchers', sa.Column('linked_caisse_voucher_ids', sa.JSON(), nullable=True))
    op.add_column('requests', sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='requestpriority'), nullable=True))
    op.add_column('requests', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('category', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('sla_deadline', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('manager_validator_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('manager_validated_at', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('finance_validator_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('finance_validated_at', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('linked_product_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('linked_purchase_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'users', ['finance_validator_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'purchase_requests', ['linked_purchase_request_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'users', ['manager_validator_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'products', ['linked_product_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'linked_purchase_request_id')
    op.drop_column('requests', 'linked_product_id')
    op.drop_column('requests', 'finance_validated_at')
    op.drop_column('requests', 'finance_validator_id')
    op.drop_column('requests', 'manager_validated_at')
    op.drop_column('requests', 'manager_validator_id')
    op.drop_column('requests', 'resolved_at')
    op.drop_column('requests', 'sla_deadline')
    op.drop_column('requests', 'category')
    op.drop_column('requests', 'department_id')
    op.drop_column('requests', 'priority')
    op.drop_column('bank_vouchers', 'linked_caisse_voucher_ids')
    # ### end Alembic commands ###
