"""Add phase 1 and 2 models

Revision ID: cbdebf889dc9
Revises: 4ca9f05c0207
Create Date: 2026-07-20 09:01:31.736097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdebf889dc9'
down_revision: Union[str, Sequence[str], None] = '4ca9f05c0207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_code'), 'clients', ['code'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('project_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', name='phasestatus'), nullable=True),
    sa.Column('completion_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_phases_id'), 'project_phases', ['id'], unique=False)
    op.create_table('project_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('achieved_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACHIEVED', 'DELAYED', name='milestonestatus'), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['project_phases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_milestones_id'), 'project_milestones', ['id'], unique=False)
    op.add_column('attendances', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendances', 'projects', ['project_id'], ['id'])
    op.add_column('facility_requests', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'facility_requests', 'projects', ['project_id'], ['id'])
    op.add_column('it_requests', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'it_requests', 'projects', ['project_id'], ['id'])
    op.add_column('projects', sa.Column('status', sa.Enum('STUDY', 'PLANNED', 'APPROVED', 'ONGOING', 'SUSPENDED', 'DELAYED', 'BLOCKED', 'VALIDATION', 'FINISHED', 'CLOSED', 'CANCELED', name='projectstatus'), nullable=False, server_default='STUDY'))
    op.add_column('projects', sa.Column('project_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('chef_projet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'employees', ['chef_projet_id'], ['id'])
    op.add_column('stock_movements', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'project_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'chef_projet_id')
    op.drop_column('projects', 'client_id')
    op.drop_column('projects', 'is_archived')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'project_type')
    op.drop_column('projects', 'status')
    op.drop_constraint(None, 'it_requests', type_='foreignkey')
    op.drop_column('it_requests', 'project_id')
    op.drop_constraint(None, 'facility_requests', type_='foreignkey')
    op.drop_column('facility_requests', 'project_id')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'project_id')
    op.drop_index(op.f('ix_project_milestones_id'), table_name='project_milestones')
    op.drop_table('project_milestones')
    op.drop_index(op.f('ix_project_phases_id'), table_name='project_phases')
    op.drop_table('project_phases')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_code'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
