"""Add milestones and weight to tasks

Revision ID: dd8d677bf784
Revises: 007f3c18eeb0
Create Date: 2026-07-22 10:07:19.348390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8d677bf784'
down_revision: Union[str, Sequence[str], None] = '007f3c18eeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_budgets', 'allocated_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
    op.alter_column('project_expenses', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False)
    op.add_column('project_milestones', sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('purchase_order_lines', 'unit_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
    op.add_column('tasks', sa.Column('milestone_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('weight', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('fk_tasks_milestone_id', 'tasks', 'project_milestones', ['milestone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'weight')
    op.drop_column('tasks', 'milestone_id')
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('purchase_order_lines', 'unit_price',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('project_milestones', 'order_index')
    op.alter_column('project_expenses', 'amount',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('project_budgets', 'allocated_amount',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
