"""Add project assignments

Revision ID: f0e5849fed4f
Revises: dd8d677bf784
Create Date: 2026-07-22 16:40:01.411367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e5849fed4f'
down_revision: Union[str, Sequence[str], None] = 'dd8d677bf784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_budgets', 'allocated_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
    op.alter_column('project_expenses', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False)
    op.alter_column('purchase_order_lines', 'unit_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('purchase_order_lines', 'unit_price',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('project_expenses', 'amount',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('project_budgets', 'allocated_amount',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
